/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/useGLTF";

import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";

type GLTFResult = GLTF & {
  nodes: {
    PurpleJohn: THREE.Mesh;
  };
  materials: {
    PurpleJohnMat: THREE.MeshStandardMaterial;
  };
};

const FILE_URL =
  "https://d27rt3a60hh1lx.cloudfront.net/models/Spaces4_3-1604713258/spacesvr_04.3.glb";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(FILE_URL) as GLTFResult;
  return (
    <group ref={group} {...props}>
      <group position-y={6.5}>
        <mesh
          material={materials.PurpleJohnMat}
          geometry={nodes.PurpleJohn.geometry}
          name="PurpleJohn"
        />
      </group>
    </group>
  );
}

useGLTF.preload(FILE_URL);
