/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/useGLTF";

import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";

type GLTFResult = GLTF & {
  nodes: {
    BlueJohn: THREE.Mesh;
  };
  materials: {
    BlueJohnMat: THREE.MeshStandardMaterial;
  };
};

const FILE_URL =
  "https://d27rt3a60hh1lx.cloudfront.net/models/Spaces4_2-1604713175/spacesvr_04.2.glb";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(FILE_URL) as GLTFResult;
  return (
    <group ref={group} {...props}>
      <group>
        <mesh
          material={materials.BlueJohnMat}
          geometry={nodes.BlueJohn.geometry}
          name="BlueJohn"
          rotation={[0, -0.8117, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload(FILE_URL);
