/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/useGLTF";

import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";

type GLTFResult = GLTF & {
  nodes: {
    ["1decoration"]: THREE.Mesh;
    ["1structure"]: THREE.Mesh;
    ["1floor"]: THREE.Mesh;
    ["2bench"]: THREE.Mesh;
    ["2structure"]: THREE.Mesh;
    ["2floor"]: THREE.Mesh;
    ["3decoration"]: THREE.Mesh;
    ["3structure"]: THREE.Mesh;
    ["3floor"]: THREE.Mesh;
    ["4bench"]: THREE.Mesh;
    ["4structure"]: THREE.Mesh;
    ["4floor"]: THREE.Mesh;
  };
  materials: {
    Glass: THREE.MeshStandardMaterial;
    ["1.structure"]: THREE.MeshStandardMaterial;
    ["1.floor"]: THREE.MeshStandardMaterial;
    ["2.bench"]: THREE.MeshStandardMaterial;
    ["2.structure"]: THREE.MeshStandardMaterial;
    ["2.floor"]: THREE.MeshStandardMaterial;
    ["3.structure"]: THREE.MeshStandardMaterial;
    ["3.floor"]: THREE.MeshStandardMaterial;
    ["4.bench"]: THREE.MeshStandardMaterial;
    ["4.structure"]: THREE.MeshStandardMaterial;
    ["4.floor"]: THREE.MeshStandardMaterial;
  };
};

const FILE_URL =
  "https://d27rt3a60hh1lx.cloudfront.net/models/SpacesVR1-1604620376/spacesvr_00.glb";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(FILE_URL) as GLTFResult;
  return (
    <group ref={group} {...props}>
      <group>
        <group name="1about">
          <mesh
            material={materials.Glass}
            geometry={nodes["1decoration"].geometry}
            name="1decoration"
          />
          <mesh
            material={materials["1.structure"]}
            geometry={nodes["1structure"].geometry}
            name="1structure"
          />
          <mesh
            material={materials["1.floor"]}
            geometry={nodes["1floor"].geometry}
            name="1floor"
          />
        </group>
        <group name="2services">
          <mesh
            material={materials["2.bench"]}
            geometry={nodes["2bench"].geometry}
            name="2bench"
          />
          <mesh
            material={materials["2.structure"]}
            geometry={nodes["2structure"].geometry}
            name="2structure"
          />
          <mesh
            material={materials["2.floor"]}
            geometry={nodes["2floor"].geometry}
            name="2floor"
            rotation={[0, -1.5705, 0]}
          />
        </group>
        <group name="3portfolio" rotation={[-Math.PI, 0, -Math.PI]}>
          <mesh
            material={materials.Glass}
            geometry={nodes["3decoration"].geometry}
            name="3decoration"
          />
          <mesh
            material={materials["3.structure"]}
            geometry={nodes["3structure"].geometry}
            name="3structure"
            rotation={[Math.PI, 0, Math.PI]}
          />
          <mesh
            material={materials["3.floor"]}
            geometry={nodes["3floor"].geometry}
            name="3floor"
            rotation={[0, 0, 0]}
          />
        </group>
        <group name="4contact" rotation={[-Math.PI, 0, -Math.PI]}>
          <mesh
            material={materials["4.bench"]}
            geometry={nodes["4bench"].geometry}
            name="4bench"
            rotation={[Math.PI, 0, Math.PI]}
          />
          <mesh
            material={materials["4.structure"]}
            geometry={nodes["4structure"].geometry}
            name="4structure"
            rotation={[Math.PI, 0, Math.PI]}
          />
          <mesh
            material={materials["4.floor"]}
            geometry={nodes["4floor"].geometry}
            name="4floor"
            rotation={[0, -1.5705, 0]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(FILE_URL);
