/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from "three";
import React, { useMemo, useRef } from "react";
import { useFrame, useLoader } from "react-three-fiber";
import { GLTFLoader, GLTF } from "three/examples/jsm/loaders/GLTFLoader";
import { draco } from "drei";
import { ModelProps } from "../types/model";
import { loadModel } from "../services/loader";
import { Color, Material } from "three";

type GLTFResult = GLTF & {
  nodes: {
    GODWHOLE: THREE.Mesh;
    DUDEWHOLE: THREE.Mesh;
    DUDEMESH: THREE.Mesh;
    GODMESH: THREE.Mesh;
  };
};

type ChadProps = {
  color: Color;
} & ModelProps;

export default function Model(props: ChadProps) {
  const { useEnvStore, color } = props;

  const setLoading = useEnvStore((st) => st.setLoading);
  const group = useRef<THREE.Group>();
  const { nodes } = useLoader<GLTFResult>(
    GLTFLoader,
    "https://d27rt3a60hh1lx.cloudfront.net/content/chadknight/ChadKnight6/ChadKnight6.glb",
    loadModel(setLoading)
  );

  const wireMaterialProps = {
    wireframe: true,
    color: color,
  };
  const wireframeMaterial = useMemo(
    () => new THREE.MeshBasicMaterial(wireMaterialProps),
    [wireMaterialProps]
  );

  const glowMaterialProps = {
    color: color,
    transparent: true,
    opacity: 0.3,
  };
  const glowMaterial = useMemo(
    () => new THREE.MeshBasicMaterial(glowMaterialProps),
    [glowMaterialProps]
  );

  // useFrame(({ clock }) => {
  //   if (group.current) {
  //     group.current.rotation.y = -clock.getElapsedTime() / 20;
  //   }
  // });

  // (nodes.DUDEWHOLE.material as Material).transparent = true;
  // (nodes.DUDEWHOLE.material as Material).opacity = 0.999;

  const WIREFRAME_SCALE = 1;

  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={[327, 327, 327]}>
        <mesh
          material={nodes.GODWHOLE.material}
          geometry={nodes.GODWHOLE.geometry}
          rotation={[0, 0, 0]}
        />
        <mesh
          material={nodes.DUDEWHOLE.material}
          geometry={nodes.DUDEWHOLE.geometry}
          rotation={[0, 0, 0]}
        />
        <group scale={[WIREFRAME_SCALE, WIREFRAME_SCALE, WIREFRAME_SCALE]}>
          <mesh
            material={wireframeMaterial}
            geometry={nodes.DUDEMESH.geometry}
            scale={[1.01, 1.01, 1.01]}
          />
          <mesh
            material={wireframeMaterial}
            geometry={nodes.GODMESH.geometry}
            rotation={[0, 0, 0]}
            scale={[1.01, 1.01, 1.01]}
          />
        </group>
      </group>
    </group>
  );
}
