/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from "three";
import React, { useMemo, useRef } from "react";
import { useFrame, useLoader } from "react-three-fiber";
import { GLTFLoader, GLTF } from "three/examples/jsm/loaders/GLTFLoader";
import { draco } from "drei";
import { ModelProps } from "../types/model";
import { loadModel } from "../services/loader";
import { Color, Material } from "three";

type GLTFResult = GLTF & {
  nodes: {
    GODINTERIOR: THREE.Mesh;
    DUDEINTERIOR: THREE.Mesh;
    DUDEEXTERIOR: THREE.Mesh;
    GODEXTERIOR: THREE.Mesh;
  };
};

type ChadProps = {
  color: Color;
} & ModelProps;

export default function Model(props: ChadProps) {
  const { useEnvStore, color } = props;

  const setLoading = useEnvStore((st) => st.setLoading);
  const group = useRef<THREE.Group>();
  const { nodes } = useLoader<GLTFResult>(
    GLTFLoader,
    "https://d27rt3a60hh1lx.cloudfront.net/content/chadknight/ChadKnight7/ChadKnight7.glb",
    loadModel(setLoading)
  );

  const wireMaterialProps = {
    wireframe: true,
    color: color,
    emissive: 0x000000,
    emissiveIntensity: 5,
  };
  const wireframeMaterial = useMemo(
    () => new THREE.MeshLambertMaterial(wireMaterialProps),
    [wireMaterialProps]
  );

  // useFrame(({ clock }) => {
  //   if (group.current) {
  //     group.current.rotation.y = -clock.getElapsedTime() / 20;
  //   }
  // });

  // (nodes.DUDEWHOLE.material as Material).transparent = true;
  // (nodes.DUDEWHOLE.material as Material).opacity = 0.999;

  const WIREFRAME_SCALE = 1;

  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={[327, 327, 327]}>
        <mesh
          material={nodes.GODEXTERIOR.material}
          geometry={nodes.GODEXTERIOR.geometry}
          rotation={[0, 0, 0]}
        />
        <mesh
          material={nodes.DUDEEXTERIOR.material}
          geometry={nodes.DUDEEXTERIOR.geometry}
          rotation={[0, 0, 0]}
        />
        {/*<mesh*/}
        {/*    material={nodes.GODEXTERIOR.material}*/}
        {/*    geometry={nodes.DUDEINTERIOR.geometry}*/}
        {/*/>*/}
        {/*<mesh*/}
        {/*    material={nodes.GODEXTERIOR.material}*/}
        {/*    geometry={nodes.GODINTERIOR.geometry}*/}
        {/*/>*/}
        <group scale={[WIREFRAME_SCALE, WIREFRAME_SCALE, WIREFRAME_SCALE]}>
          <mesh
            material={wireframeMaterial}
            geometry={nodes.DUDEINTERIOR.geometry}
          />
          <mesh
            material={wireframeMaterial}
            geometry={nodes.GODINTERIOR.geometry}
          />
        </group>
      </group>
    </group>
  );
}
