/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from "three";
import React, { useEffect, useRef } from "react";
import { useLoader } from "react-three-fiber";
import { GLTFLoader, GLTF } from "three/examples/jsm/loaders/GLTFLoader";
import { draco } from "drei";
import { ModelProps } from "types/model";
import { loadModel } from "services/loader";
import { useTrimeshCollision } from "services/collision";
import { BufferGeometry } from "three";

type GLTFResult = GLTF & {
  nodes: {
    COLLIDERS: THREE.Mesh;
    LEVEL3: THREE.Mesh;
    LEVEL2: THREE.Mesh;
    LEVEL1: THREE.Mesh;
    LEVEL3RAILS: THREE.Mesh;
    STAIR1: THREE.Mesh;
    STAIR2: THREE.Mesh;
    LEVEL2RAILS: THREE.Mesh;
    STAIR3: THREE.Mesh;
    STAIR4: THREE.Mesh;
    LEVEL1RAILS: THREE.Mesh;
  };
  materials: {
    ["LEVEL.MATERIAL"]: THREE.MeshStandardMaterial;
    ["RAIL.MATERIAL"]: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: ModelProps) {
  const { useEnvStore } = props;

  const setLoading = useEnvStore((st) => st.setLoading);
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useLoader<GLTFResult>(
    GLTFLoader,
    "https://d27rt3a60hh1lx.cloudfront.net/models/ChadGallery7/ChadGallery7.glb",
    loadModel(setLoading)
  );

  useEffect(() => {
    if (group.current) {
      group.current.traverse((obj) => (obj.frustumCulled = false));
    }
  }, []);

  const collision = useTrimeshCollision(
    (nodes.COLLIDERS.geometry as BufferGeometry)
      .clone()
      .translate(0, 0.0094, 0)
      .translate(0, -0.005, 0)
      .scale(80, 80, 80)
  );

  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={[80, 80, 80]}>
        <group position={[0, -0.005, 0]}>
          {/*<mesh geometry={nodes.COLLIDERS.geometry} position={[0, 0.0094, 0]}>*/}
          {/*  <meshBasicMaterial*/}
          {/*    attach="material"*/}
          {/*    color="red"*/}
          {/*    transparent={true}*/}
          {/*    wireframe={true}*/}
          {/*  />*/}
          {/*</mesh>*/}
          <mesh
            material={materials["LEVEL.MATERIAL"]}
            geometry={nodes.LEVEL3.geometry}
            position={[0.000685, 0.053645, -0.00036]}
          />
          <mesh
            material={materials["LEVEL.MATERIAL"]}
            geometry={nodes.LEVEL2.geometry}
            position={[0.000685, 0.003645, -0.00036]}
          />
          <mesh
            material={materials["LEVEL.MATERIAL"]}
            geometry={nodes.LEVEL1.geometry}
            position={[0.000685, -0.046355, -0.00036]}
          />
          <mesh
            material={materials["RAIL.MATERIAL"]}
            geometry={nodes.LEVEL3RAILS.geometry}
            position={[0, 0.059645, 0]}
          />
          <mesh
            material={materials["RAIL.MATERIAL"]}
            geometry={nodes.STAIR1.geometry}
            position={[0.326797, 0.029645, -0.05158]}
          />
          <mesh
            material={materials["RAIL.MATERIAL"]}
            geometry={nodes.STAIR2.geometry}
            position={[-0.328167, 0.029645, 0.0523]}
          />
          <mesh
            material={materials["RAIL.MATERIAL"]}
            geometry={nodes.LEVEL2RAILS.geometry}
            position={[0, 0.009645, 0]}
          />
          <mesh
            material={materials["RAIL.MATERIAL"]}
            geometry={nodes.STAIR3.geometry}
            position={[0.326797, -0.020355, -0.05158]}
          />
          <mesh
            material={materials["RAIL.MATERIAL"]}
            geometry={nodes.STAIR4.geometry}
            position={[-0.328167, -0.020355, 0.0523]}
          />
          <mesh
            material={materials["RAIL.MATERIAL"]}
            geometry={nodes.LEVEL1RAILS.geometry}
            position={[0, -0.040355, 0]}
          />
        </group>
      </group>
    </group>
  );
}
