/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useLoader } from "react-three-fiber";
import { GLTFLoader, GLTF } from "three/examples/jsm/loaders/GLTFLoader";
import { loadModel } from "../services/loader";
import { ModelProps } from "../types/model";

type GLTFResult = GLTF & {
  nodes: {
    SpacesGalery3: THREE.Mesh;
  };
  materials: {
    OUTSIDE: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: ModelProps) {
  const { useEnvStore } = props;
  const setLoading = useEnvStore((st) => st.setLoading);
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useLoader<GLTFResult>(
    GLTFLoader,
    "https://gltfloaders.s3-us-west-1.amazonaws.com/SpacesGallery3.gltf",
    loadModel(setLoading)
  );
  materials["OUTSIDE"].side = THREE.DoubleSide;
  return (
    <group scale={[100, 100, 100]} ref={group} {...props} dispose={null}>
      <mesh
        material={materials.OUTSIDE}
        geometry={nodes.SpacesGalery3.geometry}
      />
    </group>
  );
}
