/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/useGLTF";

import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";

type GLTFResult = GLTF & {
  nodes: {
    CENTERPIECE: THREE.Mesh;
  };
  materials: {
    CENTER: THREE.MeshStandardMaterial;
  };
};

const FILE_URL =
  "https://d27rt3a60hh1lx.cloudfront.net/models/WolfHead-1604045583/WolfHead_noPodium.glb";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(FILE_URL) as GLTFResult;
  return (
    <group ref={group} {...props}>
      <mesh
        material={materials.CENTER}
        geometry={nodes.CENTERPIECE.geometry}
        name="CENTERPIECE"
        rotation-y={Math.PI}
      />
    </group>
  );
}

useGLTF.preload(FILE_URL);
