/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useRef } from "react";
import { useGLTF } from "@react-three/drei/useGLTF";

import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";

type GLTFResult = GLTF & {
  nodes: {
    WHEELS: THREE.Mesh;
    SKATEBOARD: THREE.Mesh;
    WHEELS_1: THREE.Mesh;
    SKATEBOARD_1: THREE.Mesh;
    WHEELS_2: THREE.Mesh;
    SKATEBOARD_2: THREE.Mesh;
    Plane: THREE.Mesh;
    RAILING: THREE.Mesh;
    SKATEBOARD_3: THREE.Mesh;
    BENCH: THREE.Mesh;
    tree_032: THREE.Mesh;
    tree_031: THREE.Mesh;
    tree_01: THREE.Mesh;
    log_01: THREE.Mesh;
    stamp: THREE.Mesh;
    tree_02: THREE.Mesh;
    tree_03: THREE.Mesh;
    RoadBlockade_01: THREE.Mesh;
  };
  materials: {
    ["SKATEBOARD.MAT"]: THREE.MeshStandardMaterial;
    ["PLYWOOD.MAT"]: THREE.MeshStandardMaterial;
    ["RAIL.MAT"]: THREE.MeshStandardMaterial;
    ["BENCH.MAT"]: THREE.MeshStandardMaterial;
    TREES: THREE.MeshStandardMaterial;
    ["ROADBLOCK.MAT"]: THREE.MeshStandardMaterial;
  };
};

const FILE_URL =
  "https://d27rt3a60hh1lx.cloudfront.net/models/WolvesDecorations-1604114022/TerrainAssets_01.glb";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(FILE_URL) as GLTFResult;

  const SCALE = 5;

  return (
    <group ref={group} {...props}>
      <group scale={[SCALE, SCALE, SCALE]}>
        <group position-y={0.813}>
          <group name="SKATE2" rotation={[-1.2157, -1.051, -3.0961]}>
            <mesh
              material={nodes.WHEELS.material}
              geometry={nodes.WHEELS.geometry}
              name="WHEELS"
              position={[-1.5232, 0.0652, -2.5188]}
            />
            <mesh
              material={materials["SKATEBOARD.MAT"]}
              geometry={nodes.SKATEBOARD.geometry}
              name="SKATEBOARD"
              position={[-1.5442, 0.0355, -2.5175]}
            />
          </group>
          <group name="SKATE1" rotation={[-1.5984, -0.5192, -0.0101]}>
            <mesh
              material={nodes.WHEELS_1.material}
              geometry={nodes.WHEELS_1.geometry}
              name="WHEELS_1"
              position={[2.2532, -0.5146, -1.37]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials["SKATEBOARD.MAT"]}
              geometry={nodes.SKATEBOARD_1.geometry}
              name="SKATEBOARD_1"
              position={[2.2322, -0.5444, -1.3687]}
              rotation={[0, 0, 0]}
            />
          </group>
          <group name="SKATE">
            <mesh
              material={nodes.WHEELS_2.material}
              geometry={nodes.WHEELS_2.geometry}
              name="WHEELS_2"
              position={[-0.0677, -0.0662, 3.1903]}
            />
            <mesh
              material={materials["SKATEBOARD.MAT"]}
              geometry={nodes.SKATEBOARD_2.geometry}
              name="SKATEBOARD_2"
              position={[-0.0887, -0.096, 3.1916]}
            />
          </group>
          <group name="BUTTEOBJECTS">
            <mesh
              material={materials["PLYWOOD.MAT"]}
              geometry={nodes.Plane.geometry}
              name="Plane"
              rotation={[0.2851, 0, 0]}
            />
            <mesh
              material={materials["RAIL.MAT"]}
              geometry={nodes.RAILING.geometry}
              name="RAILING"
            />
            <mesh
              material={nodes.SKATEBOARD_3.material}
              geometry={nodes.SKATEBOARD_3.geometry}
              name="SKATEBOARD_3"
              rotation={[0, -Math.PI / 3, -Math.PI]}
            />
            <mesh
              material={materials["BENCH.MAT"]}
              geometry={nodes.BENCH.geometry}
              name="BENCH"
              rotation={[0, 0.0377, 0]}
            />
          </group>
          <group name="BUTTETREES">
            <mesh
              material={materials.TREES}
              geometry={nodes.tree_032.geometry}
              name="tree_032"
              rotation={[0, 1.5262, 0]}
              scale={[0.1451, 0.1451, 0.1451]}
            />
            <mesh
              material={materials.TREES}
              geometry={nodes.tree_031.geometry}
              name="tree_031"
              rotation={[-Math.PI, 0.2191, Math.PI]}
              scale={[0.1451, 0.1451, 0.1451]}
            />
            <mesh
              material={materials.TREES}
              geometry={nodes.tree_01.geometry}
              name="tree_01"
              rotation={[0, 0, 0]}
              scale={[0.1451, 0.1451, 0.1451]}
            />
            <mesh
              material={materials.TREES}
              geometry={nodes.log_01.geometry}
              name="log_01"
              rotation={[Math.PI, 0.8727, -2.0928]}
              scale={[0.1451, 0.1451, 0.1451]}
            />
            <mesh
              material={materials.TREES}
              geometry={nodes.stamp.geometry}
              name="stamp"
              rotation={[0, 0, 0]}
              scale={[0.1451, 0.1451, 0.1451]}
            />
            <mesh
              material={materials.TREES}
              geometry={nodes.tree_02.geometry}
              name="tree_02"
              rotation={[0, 0, 0]}
              scale={[0.1451, 0.1451, 0.1451]}
            />
            <mesh
              material={materials.TREES}
              geometry={nodes.tree_03.geometry}
              name="tree_03"
              rotation={[0, -0.8322, 0]}
              scale={[0.1451, 0.1451, 0.1451]}
            />
          </group>
          <mesh
            material={materials["ROADBLOCK.MAT"]}
            geometry={nodes.RoadBlockade_01.geometry}
            name="RoadBlockade_01"
            rotation={[0, -0.5681, 0]}
            scale={[100, 100, 100]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(FILE_URL);
